Scan and map transforms
flowcean/flowcean pull request #187
Opened 2024-12-19 14:30 UTC by mknitt

Depends on #163 

This adds functions to extract features from a laser scan and an occupancy grid map. 

Not sure if I should create transforms for that, or if the necessary functions should just remain in the here added python files in the example folder. @ChristianWieck What do you think?

2025-01-09 08:30 UTC, ChristianWieck requested changes
Before we merge this PR, we should try to separate the "new" changes from the tweaking of existing code. For example, the rosbag environment changes a lot and I'm not in a good position to review those changes. I would suggest you open a separate PR for them.

Regarding the helper functions: If their use is limited to your example, I'm fine with keeping them as loose files in the examples folder. However, if we can generalise them to arbitrary images (e.g. line detection might be useful for others too?), we should make a transformation out of them. This is closely related to the whole "higher dimensional data" thing that we haven't discussed yet...

2025-01-09 08:30 UTC, ChristianWieck commented on pyproject.toml
> +    "PyQt5_sip==12.16.1",
Can you move the dependencies into your example? We don't require them for flowcean but "just" for the example. See https://github.com/flowcean/flowcean/blob/9ea9664e34464c998fda77c79533dfdaf89c34ee/examples/coffee_machine/run.py#L1C1-L6C6.

2025-01-21 08:44 UTC, mknitt commented on pyproject.toml
> +    "PyQt5_sip==12.16.1",
I moved the dependencies into the example.

2025-01-21 08:55 UTC, mknitt commented on pyproject.toml
> +    "PyQt5_sip==12.16.1",
The current implementation of the rosbag environment does not support scan and map data to be loaded. So, this PR requires the rosbag environment to be changed. That's why the changes to the rosbag environment are included in this PR. Who would you suggest for reviewing the changes to the rosbag environment? I propose that we keep the changes related to the rosbag environment in this PR for the sake of simplicity. 

Regarding the helper functions: I propose we keep them in this way for now and do the generalization to arbitrary images once another use case requires line detection. What do you think?

2025-02-05 07:04 UTC, ChristianWieck reviewed
As this is only relevant to your example, I'm fine with merging as-is.

2025-02-05 07:04 UTC, ChristianWieck commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
These dependencies are'n listed anywhere, are they? Can you add them to the example "dependency comment"?

2025-02-05 07:04 UTC, ChristianWieck commented on examples/robot_localization_failure/utils.py
> +    return roll, pitch, yaw
This probably works, but why aren't you using https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html? `scipy` is a dependency of flowcean anyway.

2025-02-11 09:43 UTC, mknitt commented on examples/robot_localization_failure/utils.py
> +    return roll, pitch, yaw
Thanks, good tip! I am using scipy for this now.

2025-02-11 12:10 UTC, mknitt commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
I moved them into the dev-dependencies.

2025-02-11 15:42 UTC, mknitt commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
I had to move them back to the dependencies because the CI checks would not run through, although the dependencies are in the example dependency comment.

2025-02-11 15:45 UTC, mknitt commented
> As this is only relevant to your example, I'm fine with merging as-is.

Since this comment, I moved the scripts from the example folder to a single transform, added some more documentation, and improved the execution speed.

2025-02-12 06:36 UTC, ChristianWieck commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
Hmm that's strange. @schmidma do you have an idea why this might happen? I would rather not have open-cv as a flowcean dependency...

2025-02-14 13:21 UTC, mknitt commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
As we discussed, the dependencies are required because they are needed for the transform itself and not the run.py of the example. Previously, I had the plotting in a utils.py in the example folder, but I think it is nice for developers to tune the transform and getting some visual feedback via the plots. As long as this does not break anything else, I vote for just accepting to have the dependencies for now. 

@ChristianWieck What do you think?

2025-02-17 07:30 UTC, ChristianWieck commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
Okay for me. I guess with #216 we can modularize our dependencies more and allow the user to install only those they need.

2025-02-17 07:47 UTC, ChristianWieck commented on src/flowcean/transforms/scan_map.py
> +        sensor_pose_topic: str = "/amcl_pose",
Do we need this strong ROS coupling here? I believe a flowcean transform shoudn't assume that the data comes from ros but rather work on "arbitrary pointcloud"?

2025-02-17 07:47 UTC, ChristianWieck commented on src/flowcean/transforms/scan_map.py
> +            ).as_euler("xyz", degrees=False)[2]
Just an implementation detail: Do you really want to use "xyz"? Whenever I wanted to convert a quaternion into a yaw, "zyx" worked more reliably.

2025-02-17 07:47 UTC, ChristianWieck commented on src/flowcean/transforms/scan_map.py
I think this transform is highly specialised for your use case and can't really be used outside of it. While that's not a problem in itself, I would generally prefer to move the transform to the "example" folder, since it can't be used by a broad audience outside of that folder. This could work as an example of "how to write and use custom transforms".

2025-02-17 13:31 UTC, mknitt commented on src/flowcean/transforms/scan_map.py
> +        sensor_pose_topic: str = "/amcl_pose",
Most people that have LiDAR scan data and occlusion maps use ROS. Also, I followed your other advice and moved everything into a `custom_transforms` folder in the robot_localization_failure example. Therefore, we can keep the strong ROS coupling here.

2025-02-17 13:37 UTC, mknitt commented on src/flowcean/transforms/scan_map.py
You are right, that makes more sense. I moved this transform and `ParticleCloudStats` another use case specific transform into the "example" folder.

2025-02-17 13:49 UTC, mknitt commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
Now that the transforms are moved into the example, I removed the dependencies for OpenCV and Matplotlib from the `pyproject.toml`.

2025-02-18 06:31 UTC, ChristianWieck commented on pyproject.toml
With the new structure and the transform moved into a example, those dependencies should be not necessary anymore, no?

2025-02-18 06:38 UTC, ChristianWieck commented on src/flowcean/transforms/scan_map.py
> +            ).as_euler("xyz", degrees=False)[2]
Actually there is a difference, because with "xyz" small roll and pitch movements will affect your calculated yaw angle, whereas with "zyx" the yaw angle is independent of such movements.

2025-02-18 06:42 UTC, ChristianWieck commented on src/flowcean/transforms/scan_map.py
> +        sensor_pose_topic: str = "/amcl_pose",
I'm still not completly convinced that these transforms need such strong coupling but for the sake of getting this merged, we can keep it as-is for now.

2025-02-18 06:44 UTC, ChristianWieck commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
To be honhest I'm not sure if the `dev-dependencies` are the right place for those. My understanding of these was to include tools which are required during developtment but not deployment (such as `ruff`). If we keep the transform specific to on example I would strongly vote to exclude `open-cv` and `matplotlib` from the `pyproject.toml` and only put them into the example dependencies / the readme.

2025-02-18 14:07 UTC, ChristianWieck commented on examples/robot_localization_failure/utils.py
> +import matplotlib.pyplot as plt
Decided to leave them as regular dependencies for now. I got a plan how to fix this.

2025-02-18 14:07 UTC, ChristianWieck submitted a review, later dismissed

2025-02-18 15:04 UTC, SM20598 approved these changes

2025-02-18 15:05 UTC, merged