Added transforms for up- and downsampling
flowcean/flowcean pull request #23
Opened 2024-05-06 14:17 UTC by mknitt

Adds transforms and tests for up- and downsampling of time series data.

Required for #15

2024-05-08 07:47 UTC, schmidma requested changes
some minor remarks and suggestions

2024-05-08 07:47 UTC, schmidma commented on src/flowcean/transforms/downsample.py
> +            "last" or "mean".
```suggestion
        time_column: The name of the time column.
        sampling_rate: The sampling rate to downsample to.
        value: The value to use for the downsampling. Can be "first", "last" or "mean".
```

2024-05-08 07:47 UTC, schmidma commented on src/flowcean/transforms/downsample.py
> +        time_column (str): The name of the time column.
we usually call these "columns" _features_

2024-05-08 07:47 UTC, schmidma commented on src/flowcean/transforms/downsample.py
> +            ).agg(
You may be able to do this `group_by_dynamic` call once, as this is lazy in polars and then subsequently do the different aggregations afterwards.

Or maybe even better, first select the proper query for each version like
```
aggretation = pl.col(x)..... for x in ...
```
and then always do the
```
data = data.groupby().agg(aggregation)
```

2024-05-08 07:47 UTC, schmidma commented on src/flowcean/transforms/downsample.py
> +                pl.col(x).mean() for x in data.columns if x != self.time_column
I think there is something in polars to select all columns except one. Maybe this https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.exclude.html

2024-05-08 07:47 UTC, schmidma commented on src/flowcean/transforms/upsample.py
> +            .fill_null(strategy="forward")
expose the strategy to the user by providing it as an argument?

2024-05-08 07:47 UTC, schmidma commented on src/flowcean/transforms/upsample.py
> +        offset (str | timedelta): The offset to use for the upsampling.
```suggestion
        time_column: The name of the time column.
        sampling_rate: The sampling rate to upsample to.
        offset: The offset to use for the upsampling.
```

2024-05-08 07:47 UTC, schmidma commented on src/flowcean/transforms/upsample.py
> +    missing values using interpolation.
```suggestion
    missing values using an interpolation strategy.
```

2024-11-14 08:36 UTC, mknitt commented
Closing this PR because the functionality is already provided by #122

2024-11-14 08:36 UTC, closed without merging